name: IA Pipeline on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  linter:
    uses: Lgonrat/workflow-reusable/.github/workflows/linterIA_sinCopilot.yaml@main
  
  test-plan:
    uses: Lgonrat/workflow-reusable/.github/workflows/testPlanIA.yaml@main   
    with:
      summary_file: ${{ needs.linter.outputs.summary_output_file }}

