name: IA Linter on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  run-linter:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.get-diff.outputs.diff }}

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate PR diff
        id: get-diff
        run: |
          BASE=${{ github.event.pull_request.base.ref }}
          git fetch origin $BASE
          DIFF=$(git diff origin/$BASE...HEAD)
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Call reusable workflow
        uses: Lgonrat/workflow-reusable/.github/workflows/linterIA.yaml@main
        permissions:
        secrets: inherit
        with:
          DIFF_CONTENT: ${{ steps.get-diff.outputs.diff }}
